fieldLayouts:
  f20a8b78-7b4d-4f9e-8422-f7f6a8ffa7d1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  bd6718f0-f3f5-4faf-87b2-6a22a04f167a:
    hasUrls: true
    template: blog/_category
    uriFormat: 'blog/categories/{slug}'
structure:
  maxLevels: 1
  uid: 0a95886c-7f07-4ca4-888a-f0fb4ff3e17d
